### PR TITLE
Draft abstract for GSoC project: linked list

### PR DESCRIPTION
**Pull request by ChetanKarwa**
@milancurcic @arjenmarkus 
Here is the draft for the abstract of the linked list project.
Please let me know if any changes are needed.

### CODE REVIEW

**Comment by arjenmarkus** [comment]
Hi Chetan,

Nice start. I do not have a convenient interface to reviewing on github on
my phone, so I will do it the old-fashioned way.
"Thier" should be their
"A list" in the first part should be a linked list. Instead of necessary, I
would use "classical" or "convenient", as there are many ways to skin a cat
(figuratively speaking).
I would say that the gsoc project "aims" instead of "aimed". Or perhaps
even better "the goal of the gsoc project was" (tenses are tricky).
You left out a number of "the"s but Milan can help you with those.

Regarda,

Arjen

Op vr 30 jul. 2021 15:42 schreef ChetanKarwa ***@***.***>:

**Comment by milancurcic** [comment]
Thanks Chetan! I suggest:

* "A bunch of" -> "several"
* Mention example applications of linked lists, e.g. "has numerous applications, such as..."

What is the title? I suggest:

"Linked lists in the Fortran Standard Library"

Please submit when ready.

**Comment by ivan-pi** [comment]
>    * Mention example applications of linked lists, e.g. "has numerous applications, such as..."

First place I encountered a linked list when I began to learn programming was in a CFD code (written in C) that came with the book

> Griebel, M., Dornseifer, T., & Neunhoeffer, T. (1998). Numerical simulation in fluid dynamics: a practical introduction. SIAM.

The linked list was used to store coordinates of tracer particles injected at a certain rate at a defined point within the flow. Connecting the particles, it is possible to draw the [streaklines](https://en.wikipedia.org/wiki/Streamlines,_streaklines,_and_pathlines) of the flow. An example of what the tracer particles look like (not showing any streaklines) can be seen here: https://www.youtube.com/watch?v=jfZFez-ducs&t=38s

So the application would be essentially a self-growing container.

**Comment by milancurcic** [comment]
@ChetanKarwa Did you submit this abstract?

**Comment by arjenmarkus** [comment]
Hi Chetan, Milan,

let's meet this week to prepare the talk. My agenda has room for a meeting
on most afternoons this week (except today).

Regards,

Arjen

Op vr 3 sep. 2021 om 18:01 schreef Milan Curcic ***@***.***>:

**Pull request merged**
