### PR TITLE
Add fpm abstract

### PR DESCRIPTION
**Pull request by everythingfunctional**

### CODE REVIEW

**Comment by certik** [comment]
Is there a time to make modifications to the abstract? If not, we can just merge what is already submitted.

**Comment by everythingfunctional** [comment]
I think I can modify until tomorrow, but this is what has been submitted.

**Comment by milancurcic** [comment]
I don't want to change anything about this submission, so it can be merged IMO.

**Comment by certik** [comment]
I would like to change it to better motivate why we are implementing a package manager and not just using some other manager such as Conda. But not a day before a deadline, so let's just keep it as it is. Next time let's iterate on the abstract a little bit earlier. :)

**Comment by everythingfunctional** [comment]
Ok, I don't seem to have permission to merge it.

**Comment by milancurcic** [comment]
Okay, I will merge it now, thank you, Brad.

**Pull request merged**
