### PR TITLE
Add presentation draft

### PR DESCRIPTION
**Pull request by ivan-pi**
Hello everyone,

my sincere apologies for this very late draft. 

I am in Paderborn at the deRSE23 and will be giving a 15-min talk about Fortran-lang at 12:00 (at noon, in 5h 30min). If you have any suggestions I should be able to integrate until 10:00 AM

The organizers expect us to use their laptop for the presentation, so I decided against doing any kind of demo.

The talk is in the session _Education and Digital literacy_. In the talk I plan to stir things in that direction.

All errors are mine and mine alone.

### CODE REVIEW

**Comment by ivan-pi** [comment]
The PDF can be read here: https://github.com/fortran-lang/talks/blob/504b1eceee4d69b099a72e326290e629143a7cc6/deRSE23/deRSE23.pdf

**Comment by arjenmarkus** [comment]
I had a quick look: quite colourful :) - looks good to me, nothing to add.

Op di 21 feb. 2023 om 06:33 schreef Ivan Pribec ***@***.***>:

**Comment by jvdp1** [comment]
Dear,

Thanks for sharing. LGTM! Have fun!

Yours sincerely,

Jeremie

Le mar. 21 févr. 2023 à 06:33, Ivan Pribec ***@***.***> a
écrit :

**Comment by vmagnin** [comment]
Dear @ivan-pi ,

it's perfect. I like your author touch!

For example, the slide "Relevance of Fortran for Science" is an interesting way to show the ubiquity of Fortran.

Have fun with your presentation, and thanks for putting us in the authors list!

Vincent

**Comment by epagone** [comment]
Hi @ivan-pi,

thank you for putting together such nice presentation. The "storyline" flows really well and the appearance is consistent and pleasant. I particularly appreciated your use of quotes at slide 5 :smile: :+1: 

The only **very minor** observation from my side (**if** there is time and you agree of course, I'm still confused by time zones) is at slide 15 where the word "generics" can be typeset emphasised or between quotes since it's almost Fortran jargon.

Good luck and have fun in Paderborn. :rocket:  Thanks for including our names.

**Review by epagone — APPROVED** [review]

**Pull request merged**
